modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/noobanidus/death-backup/issues"
license="https://github.com/noobanidus/death-backup/blob/master/LICENSE"
[[mods]]
modId="deathbackup"
version="${file.jarVersion}"
displayName="Death Backup"
displayURL="https://minecraft.curseforge.com/projects/death-backup"
authors="Noobanidus"
description='''
Server-side mod to keep inventory backups when players die. These can be restored by an operator.
'''
[[dependencies.DeathBackup]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.DeathBackup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"